-- DEPRECATED — use snowflake/migrations/001 and 004 instead.
-- Legacy column-mapping REVIEW_ENTRY tables; do not apply on new environments.

USE DATABASE PM_PROD;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS REVIEW_ENTRY (
    REVIEW_ID VARCHAR PRIMARY KEY,
    UPLOAD_ID VARCHAR NOT NULL,
    PARTNER_KEY VARCHAR NOT NULL,
    FILENAME VARCHAR,
    PERIOD VARCHAR,
    SOURCE_COLUMNS VARIANT,
    SOURCE_SIGNATURE VARCHAR NOT NULL,
    MAPPING VARIANT,
    STATUS VARCHAR NOT NULL,
    VALIDATION_SOURCE VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GLOBAL_MEMORY (
    SOURCE_SIGNATURE VARCHAR PRIMARY KEY,
    SOURCE_COLUMNS VARIANT,
    MAPPING VARIANT NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR
);

CREATE TABLE IF NOT EXISTS LOCAL_MEMORY (
    PARTNER_KEY VARCHAR NOT NULL,
    SOURCE_SIGNATURE VARCHAR NOT NULL,
    SOURCE_COLUMNS VARIANT,
    MAPPING VARIANT NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PARTNER_KEY, SOURCE_SIGNATURE)
);
